version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-static
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./sample_html.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    driver: bridge